version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
    networks:
      default:

  amf:
    image: gradiant/open5gs:2.7.1
    command:
      - open5gs-amfd
    restart: on-failure
    networks:
      default:

  ausf:
    image: gradiant/open5gs:2.7.1
    command:
      - open5gs-ausfd
    restart: on-failure
    networks:
      default:

  bsf:
    image: gradiant/open5gs:2.7.1
    command:
      - open5gs-bsfd
    restart: on-failure
    networks:
      default:

  nrf:
    image: gradiant/open5gs:2.7.1
    command: open5gs-nrfd
    restart: on-failure
    networks:
      default:

  nssf:
    image: gradiant/open5gs:2.7.1
    command: open5gs-nssfd
    restart: on-failure
    networks:
      default:

  pcf:
    image: gradiant/open5gs:2.7.1
    command:
      - open5gs-pcfd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
    networks:
      default:

  scp:
    image: gradiant/open5gs:2.7.1
    command: open5gs-scpd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
    networks:
      default:

  smf:
    image: gradiant/open5gs:2.7.1
    #It is necessary to mount the configuration file if pcfr is not deployed
    volumes:
      - ./config/smf.yaml:/opt/open5gs/etc/open5gs/smf.yaml
    restart: on-failure
    command: open5gs-smfd
    networks:
      default:

  udm:
    image: gradiant/open5gs:2.7.1
    restart: on-failure
    command:
      - open5gs-udmd
    networks:
      default:

  udr:
    image: gradiant/open5gs:2.7.1
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    command:
      - open5gs-udrd
    networks:
      default:

  upf:
    image: gradiant/open5gs:2.7.1
    command:
      - open5gs-upfd
    cap_add:
      - all
    privileged: true
    restart: on-failure
    # environment:
    # ENABLE_NAT: "false"
    ports:
      - 2152:2152
    networks:
      default:

  webui:
    image: gradiant/open5gs-webui:2.7.1
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
      NODE_ENV: dev
    ports:
      - 9999:9999
    networks:
      default:

networks:
  default:
    external:
      name: docker_open5gs_default
