version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
    networks:
      default:
        ipv4_address: ${MONGO_IP}

  amf:
    image: gradiant/open5gs:2.7.1
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command:
      - open5gs-amfd
    restart: on-failure
    expose:
      - "38412/sctp"
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${AMF_IP}

  ausf:
    image: gradiant/open5gs:2.7.1
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command:
      - open5gs-ausfd
    restart: on-failure
    networks:
      default:
        ipv4_address: ${AUSF_IP}

  bsf:
    image: gradiant/open5gs:2.7.1
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command:
      - open5gs-bsfd
    restart: on-failure
    networks:
      default:
        ipv4_address: ${BSF_IP}

  nrf:
    image: gradiant/open5gs:2.7.1
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command: open5gs-nrfd
    restart: on-failure
    networks:
      default:
        ipv4_address: ${NRF_IP}

  nssf:
    image: gradiant/open5gs:2.7.1
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command: open5gs-nssfd
    restart: on-failure
    networks:
      default:
        ipv4_address: ${NSSF_IP}

  pcf:
    image: gradiant/open5gs:2.7.1
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command:
      - open5gs-pcfd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
    networks:
      default:
        ipv4_address: ${PCF_IP}

  scp:
    image: gradiant/open5gs:2.7.1
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command: open5gs-scpd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
    networks:
      default:
        ipv4_address: ${SCP_IP}

  smf:
    image: gradiant/open5gs:2.7.1
    #It is necessary to mount the configuration file if pcfr is not deployed
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    restart: on-failure
    command: open5gs-smfd
    networks:
      default:
        ipv4_address: ${SMF_IP}

  udm:
    image: gradiant/open5gs:2.7.1
    restart: on-failure
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command:
      - open5gs-udmd
    networks:
      default:
        ipv4_address: ${UDM_IP}

  udr:
    image: gradiant/open5gs:2.7.1
    restart: on-failure
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    environment:
      DB_URI: mongodb://mongo/open5gs
    command:
      - open5gs-udrd
    networks:
      default:
        ipv4_address: ${UDR_IP}

  upf:
    image: gradiant/open5gs:2.7.1
    volumes:
      - ./configs:/opt/open5gs/etc/open5gs
    command:
      - open5gs-upfd
    cap_add:
      - all
    privileged: true
    restart: on-failure
    # environment:
    # ENABLE_NAT: "false"
    ports:
      - 2152:2152
    networks:
      default:
        ipv4_address: ${UPF_IP}

  webui:
    image: gradiant/open5gs-webui:2.7.1
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
      NODE_ENV: dev
    ports:
      - 9999:9999
    networks:
      default:
        ipv4_address: ${WEBUI_IP}

networks:
  default:
    name: docker_open5gs_default
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
